### ISSUE TITLE
نحوه کبیسه شماری در این کتابخانه

### ISSUE THREAD

**Issue by itismoradi-zz** [SCR-IR/jalaliDate-Cpp#1]
کبیسه شماری در این کتابخانه برای تقویم جلالی چگونه صورت می گیرد؟ 
منظور از تقویم جلالی در این کتابخانه تقویم هجری خورشیدی است؟
ممنون میشم از جزئیات محاسبتش آگاهم کنید.

**Comment by SCR-IR** [comment]
روش محاسبه، کبیسه‌بندی ثابت ۳۳ ساله‌ی جلالی می‌باشد.

لطفاً به این مقاله مراجعه بفرمایید:
[https://github.com/SCR-IR/date-algorithms-article](https://github.com/SCR-IR/date-algorithms-article)

و نتایج این ازمایش:
[https://github.com/SCR-IR/date-algorithms-article/tree/main/JavaScript/performance](https://github.com/SCR-IR/date-algorithms-article/tree/main/JavaScript/performance)

**Comment by itismoradi-zz** [comment]
ممنون
این یعنی دوره های 29 یا بعضا 37 ساله در آن لحاظ نشده اند؟
![ویکی پدیا](https://user-images.githubusercontent.com/75095946/158272050-531d5088-7ad6-4795-968c-9f7ad952dee8.jpg)
در اینجا دوره هایی 29 یا 37 ساله وجود دارند.
من میخواهم از کتابخانه شما استفاده کنم این سوال برایم پیش آمد
الگوریتم شما چه رفتاری دارد؟
ممنون

**Comment by SCR-IR** [comment]
خیر، الگوریتمی که شما ذکر فرمودید با تقویم رسمی کشور مغایرت دارد. به‌عنوان مثال، در همین تصویر که ارسال نموده‌اید (پایین جدول) سال‌های ۱۳۰۸ و ۱۳۴۱ اصلاً با تقویم رسمی ایران مطابقت ندارند. در تقویم کشور، سال‌های ۱۳۰۹ و ۱۳۴۲ کبیسه بوده‌اند که با الگوریتم مورد استفاده‌ی خودمان نیز صحیح می‌باشد. برای بازه‌ی زمانی بین سال‌های ۱۱۷۸ تا ۱۶۳۳ هجری‌شمسی، الگوریتم‌های ۳۳ساله‌ی مورداستفاده‌ی ما دقیقاً منطبق بر تقویم رسمی کشور هستند؛ اما خارج از این بازه، هیچ الگوریتم مشخصی به رسمیت شناخته نشده و انتخاب بین الگوریتم «۳۳ساله» یا «اعتدال بهاری» به اختیار خود شماست.

**Comment by SCR-IR** [comment]
[https://jdf.scr.ir/tarikh/tahvile_sal#jn2](https://jdf.scr.ir/tarikh/tahvile_sal#jn2)

**Comment by itismoradi-zz** [comment]
> خیر، الگوریتمی که شما ذکر فرمودید با تقویم رسمی کشور مغایرت دارد. به‌عنوان مثال، در همین تصویر که ارسال نموده‌اید (پایین جدول) سال‌های ۱۳۰۸ و ۱۳۴۱ اصلاً با تقویم رسمی ایران مطابقت ندارند. در تقویم کشور، سال‌های ۱۳۰۹ و ۱۳۴۲ کبیسه بوده‌اند که با الگوریتم مورد استفاده‌ی خودمان نیز صحیح می‌باشد. برای بازه‌ی زمانی بین سال‌های ۱۱۷۸ تا ۱۶۳۳ هجری‌شمسی، الگوریتم‌های ۳۳ساله‌ی مورداستفاده‌ی ما دقیقاً منطبق بر تقویم رسمی کشور هستند؛ اما خارج از این بازه، هیچ الگوریتم مشخصی به رسمیت شناخته نشده و انتخاب بین الگوریتم «۳۳ساله» یا «اعتدال بهاری» به اختیار خود شماست.

خیلی از راهنمایی کارگشاتون متشکرم
سوال ریزی در مورد بازه 1178 شمسی تا 1633 داشتم. الگوریتم جلالی دقیقا در مورد چه روزی از سال 1178 شمسی تا 1633 شمسی درست کار میکند. روز دقیقش را نیاز دارم.
من در برنامه ام اینطور در نظر گرفته ام که کاربر باید تاریخی بین 1 فروردین 1178 شمسی الی 29 اسفند ماه 1632 شمسی وارد کند. آیا این بازه درست است یا سال 1633 هم درست کار میکند؟ بازه دقیق آن برایم مهم است.

ممنون و مچکر
مانا باشید🌹

**Comment by SCR-IR** [comment]
بله همین بازه (۱۱۷۸-۱۶۳۳ هـ.ش) صحیح است.

البته این به معنای اشتباه بودن محاسبات خارج از آن بازه نیست. بلکه برای تبدیل تاریخ خارج از آن بازه، می‌بایست کاربر انتخاب کند که تمایل دارد از چه روش کبیسه‌بندی استفاده نماید. روش‌های بسیار زیادی مطرح شده که ما در اینجا فقط به ۲ روش اشاره کردیم. این ۲ روش نامبرده در بازه‌ی زمانی ذکرشده، کاملاً نتیجه‌ی یکسان دارند و خارج از آن بازه، ممکن است در بعضی سال‌ها متفاوت باشند.

**Comment by SCR-IR** [comment]
مثلاً اگر از سال ۱۶۳۴ تا ۱۶۹۹ را بررسی کنیم، فقط در سال‌های ۱۶۳۴، ۱۶۳۵ و ۱۶۶۷، ۱۶۶۸ اختلاف دارند و بقیه‌ی ۶۲ سال دیگر را منطبق هستند.

**Comment by itismoradi-zz** [comment]
> مثلاً اگر از سال ۱۶۳۴ تا ۱۶۹۹ را بررسی کنیم، فقط در سال‌های ۱۶۳۴، ۱۶۳۵ و ۱۶۶۷، ۱۶۶۸ اختلاف دارند و بقیه‌ی ۶۲ سال دیگر را منطبق هستند.

متشکرم متوجه شدم

**Comment by SCR-IR** [comment]
🙏
